version: '3.8'
services:
  eventsystem:
    image: eventsystem
    restart: always
    depends_on:
      - "redis-eventsystem"
    ports:
      - "80:3000"
    networks:
      - eventsystem
  redis-eventsystem:
    image: redis
    command: ["redis-server", "--bind", "redis-eventsystem", "--port", "6379", "--protected-mode", "no"]
    restart: always
    networks:
      - eventsystem
networks:
  eventsystem:
    driver: bridge