version: '3.8'
services:
  eventsystem:
    image: eventsystem
    restart: always
    depends_on:
      - "redis-eventsystem"
    ports:
      - "80:3000"
  redis-eventsystem:
    image: redis
    restart: always
    configs:
      - source: redis.conf
        target: /usr/local/etc/redis/redis.conf
    networks:
      default:
        aliases:
          - redis-eventsystem