version: '3.8'
services:
  eventsystem:
    image: eventsystem
    restart: always
    depends_on:
      - "redis-eventsystem"
    ports:
      - "80:3000"
  redis-eventsystem:
    image: redis
    restart: always
    networks:
      default:
        aliases:
          - redis-eventsystem